[package]
name = "protocol"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
publish = false

[features]
client = ["dep:wayland-client"]
server = ["dep:wayland-server"]

[dependencies]
wayland-backend.workspace = true
wayland-client = { workspace = true, optional = true }
wayland-scanner.workspace = true
wayland-server = { workspace = true, optional = true }
