[package]
name = "compositor"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
publish = false

[dependencies]
calloop.workspace = true
cairo-rs.workspace = true
protocol = { workspace = true, features = ["server"] }
smithay.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
